apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: xxx
  title: xxx
  description: An example template for the scaffolder that updates a JSON file in GitLab
spec:
  owner: user:guest
  type: service

  parameters:
    - title: Fill in some steps
      required:
        - repoUrl
        - filePath
      properties:
        repoUrl:
          title: Repository URL
          type: string
          description: The URL of the GitLab repository
          ui:autofocus: true
          ui:options:
            rows: 5
        filePath:
          type: string
          title: Path to the JSON file
    - title: Update JSON
      required: []
      properties:
        updates:
          type: object
          title: Key-Value Pairs to Update
          description: Provide the key-value pairs to update in the JSON file.
          additionalProperties:
            type: string

  steps:
    - id: download-json
      name: Download JSON
      action: util:download-json
      input:
        repoUrl: ${parameters.repoUrl}
        filePath: ${parameters.filePath}

    - id: update-json
      name: Update JSON
      action: util:update-json
      input:
        repoUrl: ${parameters.repoUrl}
        filePath: ${parameters.filePath}
        updates: ${parameters.updates}

  # output:
  #   updatedJson:
  #     $ref: '#/steps/update-json/output/updatedJson'
  # output:
  #   updatedJson:
  #     type: string
  #     description: The updated JSON after modification
  #     value: '{{ steps.update-json.output.updatedJson }}'

